name: CI

on: [push]
#on:
#  push:
#    branches:
#      - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: install python dependencies
      run: pipenv sync --dev
    - name: install ansible roles
      run: pipenv run make update-vendor-role
